services:
  postgres:
    image: postgres:17
    container_name: notes-postgres

    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - notes-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: notes-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  app:
    build: .

    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/notes
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest


    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  nginx:
    image: nginx:alpine

    ports:
      - "8080:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - app
volumes:
  notes-postgres-data: