### GET notes
GET  http://localhost:8080/notes/a

###

### POST note
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": 123

}


### PUT Note
PATCH http://localhost:8080/notes/3
Content-Type: application/json

{
  "version": 1,
  "title": "New title 2"}
###

DELETE http://localhost:8080/notes/1
Content-Type: application/json

###
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": "Final smoke test",
  "content": "Created through RabbitMQ"
}
###
PATCH http://localhost:8080/notes/5
Content-Type: application/json

{
  "version": 0,

  "title": "Stale title"
}

###
POST http://localhost:8080/notes
Content-Type: application/json

{

  "title": "DB failure test",

  "content": "Must not be silently lost"

}